### ISSUE TITLE
Problems when 5th player joins lobby

### ISSUE THREAD

**Issue by Shad0wlife** [Crackdown-PD2/BigLobby3#10]
This issue actually happened on the classic BLT version of this mod at a LAN Party, but it probably does on this too.
More than 4 characters in game is fine - as long as the lobby is only 4 players or less (so bots are fine)...
BUT: as soon as the 5th player tries to join, he can't connect. Only the host is able to see him for a very short time, and the other clients in the lobby can't see him at all. Works the other way round too: the 5th player can only see the host but no other clients until he times out quickly afterwards. If he tries to join in the actual lobby, he will also crash (won't happen in the mission briefing).

Already mentioned this a while ago on the old repo (the bug was already known there): [LINK](https://github.com/polarathene/biglobby/issues/51).

Maybe we could arrange some testing with 5+ players to see if it still happens and maybe find the source of the issue (I suspect it's somewhere during the handshake with the other clients which happens after the handshake with the host afaik).

**Comment by polarathene** [comment]
I remember that type of issue being a big problem for me when using my original no PDMOD implementation via JSON and network messages(like how BLT uses the chat channels to send text that is usually meant for chat messages between players). The approach was unreliable at sending packets though, it was also discovered that the non-lua code of PD2 was getting the packets and overwriting the player id(either when sending it or receiving it, could be overflow too I guess). So it was attempted to use modified methods with an extra parameter or using an unmodified method with a string parameter that packed the player id with the actual string param for the method and unpacked when received. The handshake issues was the biggest problem to deal with and debug, lot of time spent on dealing with that with the old json method.

Later one of the well known PD2 modding community members(Spy I think, or Beard) pointed the network_settings file out which could be modified by a pdmod. If memory serves me correctly, this files contents need to match with the other players(or at least a host and client). It is possible that a change has happened which this new iteration of biglobby has not been adjusted for. Not only must that file be modified, but there is a lua part that will override the network classes, you should find two lists of methods(the network settings covers two rpcs, one is unit, the other...network? something like that, should be clear by looking at source code). When some methods are added or changed, they may need to be in one of those lists, I forget the reasoning, but again looking at the code should be clear, I'm pretty sure I commented the source code to indicate the purpose.

Beyond that information, you might have to sweep over any lua methods being altered, their function signature and original source, then compare to the biglobby modified version. I'd start at the network specific lua code :) (In a network folder iirc as I mirrored the original codebase hierachy for clarity).

**Comment by Iamgoofball** [comment]
Yeah, I'm not certain about if more network functions were added, but if they were, we can easily add them to the tweaker and the code.

**Comment by Shad0wlife** [comment]
The interesting thing is that 4 players with tons of bots worked just fine. (This was a few months ago, a few days after I posted the 2 fixes on the old repo). Only when using more actual players, the issue happened on lobby join (which is why I suspect the handshake as I said).
Anyways. The lua functions that are called with "Network:", where do they lead? Network isnt defined anywhere in the lua codebase as a "class", so I couldn't find where these calls lead. Do they end up in the stuff defined in network.settings ?

**Comment by polarathene** [comment]
@Shad0wlife Yes bots should be fine vs players. Before biglobby I had a bot spawning mod, I could have 100 bots no problem, but if something was done that would try to update their UI, due to hardcoded UI for other players it'd result in crash for them. It will be caused by one of the reasons I pointed out in my previous post.

The network class is lua binding to C++ code which we do not have access to. That code reads in the network settings file to know what methods are relevant and what their parameters are. You can see the network code I have overwrites/hooks a send function in lua, this method iirc will do some stuff then send it off to the network C++ class to handle, it'll receive network events then let the lua engine and code know about it.

I don't remember how exactly but you can expose methods, I think it was called a metatable or something like that, so if you have a way to pretty print a table/object fields in lua, you can take a class like Network to get it's methods. This works for several classes that don't have lua code other than other lua code calling their methods, some are Steam based. You can hook onto those methods too, and I had done that with some mods I made, as well as my biglobby feature I was working on that lets you filter lobbies better(by mods) and let you seamlessly join/see modded and non-modded lobbies.

**Comment by Shad0wlife** [comment]
Could not reproduce with 188 - Ran 5 Win10 VMs with Payday Biglobby in them - could go to lobby AND ingame (not actually play, my 4 core CPU couldn't do more than maybe 15 fps on each instance).
So I'll just close this for now.
