### ISSUE TITLE
Play with non-modders

### ISSUE THREAD

**Issue by Smithienious** [Crackdown-PD2/BigLobby3#27]
I want to host a modded lobby, but my friends are not willing to install the mod. Is it possible to modify the mod so non-modders can join my lobby?

**Comment by steam-test1** [comment]
It might be possible by doing the following
Replace lua/lib/network/matchmaking/_networkmatchmakingsteam.lua with the following
NetworkMatchMakingSTEAM.OPEN_SLOTS = BigLobbyGlobals:num_player_slots()
This should allow non modded users to join
Note that they will  likely crash, because of the vanilla HUD not supporting more than 4 users

If they don't crash then they will be unable to do the following:
-    Draw in preplanning
-    Pickup things like keycards
-    Pickup bags or secure bags
-    They won't appear in endgame statistics
